name = "RareLotkaVolterra"
uuid = "7f8a4234-2f47-4ba8-a777-d0896a6abc98"
authors = ["Ismaël Lajaaiti <ismael.lajaaiti@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
